package demo.proyecto1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BatchConfig implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BATCHCONFIG_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BATCHCONFIG_ID_GENERATOR", sequenceName = "BATCHCONFIG_ID_SEQ")
   private java.lang.Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL })
   @org.kie.api.definition.type.Label(value = "BatchConfigHeader")
   private demo.proyecto1.BatchConfigHeader batchConfigHeader;

   @javax.persistence.OneToMany(cascade = { javax.persistence.CascadeType.ALL })
   @org.kie.api.definition.type.Label(value = "Entornos")
   private java.util.List<demo.proyecto1.Entorno> entornos;

   @org.kie.api.definition.type.Label(value = "Tipo")
   private java.lang.String tipo;

   public BatchConfig()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public demo.proyecto1.BatchConfigHeader getBatchConfigHeader()
   {
      return this.batchConfigHeader;
   }

   public void setBatchConfigHeader(
         demo.proyecto1.BatchConfigHeader batchConfigHeader)
   {
      this.batchConfigHeader = batchConfigHeader;
   }

   public java.util.List<demo.proyecto1.Entorno> getEntornos()
   {
      return this.entornos;
   }

   public void setEntornos(java.util.List<demo.proyecto1.Entorno> entornos)
   {
      this.entornos = entornos;
   }

   public java.lang.String getTipo()
   {
      return this.tipo;
   }

   public void setTipo(java.lang.String tipo)
   {
      this.tipo = tipo;
   }

   public BatchConfig(java.lang.Long id,
         demo.proyecto1.BatchConfigHeader batchConfigHeader,
         java.util.List<demo.proyecto1.Entorno> entornos,
         java.lang.String tipo)
   {
      this.id = id;
      this.batchConfigHeader = batchConfigHeader;
      this.entornos = entornos;
      this.tipo = tipo;
   }

}