package demo.proyecto1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class BatchConfigHeader implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "BATCHCONFIGHEADER_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "BATCHCONFIGHEADER_ID_GENERATOR", sequenceName = "BATCHCONFIGHEADER_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Siglas Host")
   private java.lang.String siglasHost;

   @org.kie.api.definition.type.Label(value = "Version BBDD")
   private java.lang.String versionBBDD;

   @org.kie.api.definition.type.Label(value = "Driver BBDD")
   private java.lang.String driverBBDD;

   public BatchConfigHeader()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getSiglasHost()
   {
      return this.siglasHost;
   }

   public void setSiglasHost(java.lang.String siglasHost)
   {
      this.siglasHost = siglasHost;
   }

   public java.lang.String getVersionBBDD()
   {
      return this.versionBBDD;
   }

   public void setVersionBBDD(java.lang.String versionBBDD)
   {
      this.versionBBDD = versionBBDD;
   }

   public java.lang.String getDriverBBDD()
   {
      return this.driverBBDD;
   }

   public void setDriverBBDD(java.lang.String driverBBDD)
   {
      this.driverBBDD = driverBBDD;
   }

   public BatchConfigHeader(java.lang.Long id, java.lang.String siglasHost,
         java.lang.String versionBBDD, java.lang.String driverBBDD)
   {
      this.id = id;
      this.siglasHost = siglasHost;
      this.versionBBDD = versionBBDD;
      this.driverBBDD = driverBBDD;
   }

}