package demo.proyecto1;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Entorno implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ENTORNO_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "ENTORNO_ID_GENERATOR", sequenceName = "ENTORNO_ID_SEQ")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Tipo Entorno")
   private java.lang.String tipoEntorno;

   @org.kie.api.definition.type.Label(value = "Configuracion")
   private java.lang.Boolean config;

   @org.kie.api.definition.type.Label(value = "Usuario")
   private java.lang.String usuario;

   @org.kie.api.definition.type.Label(value = "Password")
   private java.lang.String password;

   @org.kie.api.definition.type.Label(value = "SID")
   private java.lang.String sid;

   @org.kie.api.definition.type.Label(value = "Data Source")
   private java.lang.String dataSource;

   @org.kie.api.definition.type.Label(value = "volumen")
   private java.math.BigDecimal volumen;

   @javax.persistence.ElementCollection(fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label(value = "servidores")
   private java.util.List<java.lang.String> servidores;

   public Entorno()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getTipoEntorno()
   {
      return this.tipoEntorno;
   }

   public void setTipoEntorno(java.lang.String tipoEntorno)
   {
      this.tipoEntorno = tipoEntorno;
   }

   public java.lang.Boolean getConfig()
   {
      return this.config;
   }

   public void setConfig(java.lang.Boolean config)
   {
      this.config = config;
   }

   public java.lang.String getUsuario()
   {
      return this.usuario;
   }

   public void setUsuario(java.lang.String usuario)
   {
      this.usuario = usuario;
   }

   public java.lang.String getPassword()
   {
      return this.password;
   }

   public void setPassword(java.lang.String password)
   {
      this.password = password;
   }

   public java.lang.String getSid()
   {
      return this.sid;
   }

   public void setSid(java.lang.String sid)
   {
      this.sid = sid;
   }

   public java.lang.String getDataSource()
   {
      return this.dataSource;
   }

   public void setDataSource(java.lang.String dataSource)
   {
      this.dataSource = dataSource;
   }

   public java.math.BigDecimal getVolumen()
   {
      return this.volumen;
   }

   public void setVolumen(java.math.BigDecimal volumen)
   {
      this.volumen = volumen;
   }

   public java.util.List<java.lang.String> getServidores()
   {
      return this.servidores;
   }

   public void setServidores(java.util.List<java.lang.String> servidores)
   {
      this.servidores = servidores;
   }

   public Entorno(java.lang.Long id, java.lang.String tipoEntorno,
         java.lang.Boolean config, java.lang.String usuario,
         java.lang.String password, java.lang.String sid,
         java.lang.String dataSource, java.math.BigDecimal volumen,
         java.util.List<java.lang.String> servidores)
   {
      this.id = id;
      this.tipoEntorno = tipoEntorno;
      this.config = config;
      this.usuario = usuario;
      this.password = password;
      this.sid = sid;
      this.dataSource = dataSource;
      this.volumen = volumen;
      this.servidores = servidores;
   }

}