package demo.proyecto2;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Prueba implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRUEBA_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PRUEBA_ID_GENERATOR", sequenceName = "PRUEBA_ID_SEQ")
   private java.lang.Long id;

   private java.lang.String campo1;

   private java.lang.String campo2;

   public Prueba()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCampo1()
   {
      return this.campo1;
   }

   public void setCampo1(java.lang.String campo1)
   {
      this.campo1 = campo1;
   }

   public java.lang.String getCampo2()
   {
      return this.campo2;
   }

   public void setCampo2(java.lang.String campo2)
   {
      this.campo2 = campo2;
   }

   public Prueba(java.lang.Long id, java.lang.String campo1,
         java.lang.String campo2)
   {
      this.id = id;
      this.campo1 = campo1;
      this.campo2 = campo2;
   }

}