package demo.proyecto2;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class PruebaPadre implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRUEBAPADRE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PRUEBAPADRE_ID_GENERATOR", sequenceName = "PRUEBAPADRE_ID_SEQ")
   private java.lang.Long id;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL })
   private demo.proyecto2.Prueba pruebaHijo;

   private java.lang.String campo3;

   public PruebaPadre()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public demo.proyecto2.Prueba getPruebaHijo()
   {
      return this.pruebaHijo;
   }

   public void setPruebaHijo(demo.proyecto2.Prueba pruebaHijo)
   {
      this.pruebaHijo = pruebaHijo;
   }

   public java.lang.String getCampo3()
   {
      return this.campo3;
   }

   public void setCampo3(java.lang.String campo3)
   {
      this.campo3 = campo3;
   }

   public PruebaPadre(java.lang.Long id, demo.proyecto2.Prueba pruebaHijo,
         java.lang.String campo3)
   {
      this.id = id;
      this.pruebaHijo = pruebaHijo;
      this.campo3 = campo3;
   }

}